context:
    given_name: London
    family_name: Breed
    organization: City and County of San Francisco
    address_line1: San Francisco City Hall
    address_line2: 1 Dr. Carlton B. Goodlett Place
    locality: San Francisco, CA
    postal_code: 94102
