title: Transaction Card
collated: true
default: link
variants:
  - name: no-link
    context:
        transaction_card:
            title: Why do we register businesses?
            body: "Registering is the first step to opening your business. The information helps us know who is operating."
  - name: link
    context:
          url: https://sf.gov/topics/business
          transaction_card:
              title: Business
              body: Starting, owning, and closing a business.
