handle: color-system

notes: |
  See [the Figma file](https://www.figma.com/file/B31xR1EqmSnhjSV0RuX2Ckgn/SF-Colors?node-id=62%3A1158) for more info.

context:
  groups:
    - title: Primary colors
      description: |
        These are the primary brand colors, often used for backgrounds or for general content. Blue does not have an L3 because there are a variety of different blues in use. Black is a very dark gray to subtly soften the extreme contrast.
      swatches:
        - label: Dark blue
          color: dark-blue
        - label: Blue L2
          color: blue-2
        - label: Blue L1
          color: blue-1
        - label: Black
          color: black
        - label: Dark grey
          color: dark-grey
        - label: White
          color: white
          border: black

    - title: Text colors
      description: |
        Text is typically White or Slate.
      swatches:
        - label: Slate blue
          color: slate
        - label: Light slate
          color: light-slate

    - title: Action color
      description: |
        Use Bright blue for most links, buttons, and other actionable UI (such as accordions and form elements).
      swatches:
        - label: Bright blue
          color: bright-blue

    - title: Secondary colors
      description: |
        <p>The broader secondary palette is used for highlighting and differentiating content.</p>

        <h5>L1 and L2</h5>
        <p>Use for blocking separating content areas.</p>

        <h5>L3</h5>
        <p>The L3 color is the base shade of each color. Use it for focusing attention, such as on a header.</p>

        <h5>L4</h5>
        <p>Use sparingly for hover states or when a darker color must contrast with the L3 color.</p>
      groups:
        - title: Green
          swatches:
            - label: L4
              color: green-4
              small: true
            - label: L3
              color: green-3
            - label: L2
              color: green-2
            - label: L1
              color: green-1

        - title: Red
          swatches:
            - label: L4
              color: red-4
              small: true
            - label: L3
              color: red-3
            - label: L2
              color: red-2
            - label: L1
              color: red-1

        - title: Purple
          swatches:
            - label: L4
              color: purple-4
              small: true
            - label: L3
              color: purple-3
            - label: L2
              color: purple-2
            - label: L1
              color: purple-1

        - title: Yellow
          swatches:
            - label: L4
              color: yellow-4
              small: true
            - label: L3
              color: yellow-3
            - label: L2
              color: yellow-2
            - label: L1
              color: yellow-1

        - title: Grey
          swatches:
            - label: L4
              color: grey-4
              small: true
            - label: L3
              color: grey-3
            - label: L2
              color: grey-2
            - label: L1
              color: grey-1
