context:
  colorset:
    - label: $c-black
      color: "#212123"
    - label: $c-slate
      color: "#1c3e57"
    - label: $c-dark-blue
      color: "#0c1464"
    - label: $c-bright-blue
      color: "#4f66ee"
    - label: $c-blue-2
      color: "#a9d6ea"
    - label: $c-blue-1
      color: "#edf4f7"
    - label: $c-green-4
      color: "#1b674d"
    - label: $c-green-3
      color: "#00896d"
    - label: $c-green-2
      color: "#c0e2c5"
    - label: $c-green-1
      color: "#e9f7ec"
    - label: $c-red-4
      color: "#bc4427"
    - label: $c-red-3
      color: "#c9563a"
    - label: $c-red-2
      color: "#efcabb"
    - label: $c-red-1
      color: "#f5e9e5"
    - label: $c-purple-4
      color: "#5a3e94"
    - label: $c-purple-3
      color: "#7d61b3"
    - label: $c-purple-2
      color: "#cccced"
    - label: $c-purple-1
      color: "#edebf6"
    - label: $c-yellow-4
      color: "#e7b22e"
    - label: $c-yellow-3
      color: "#f4c435"
    - label: $c-yellow-2
      color: "#f9e3a3"
    - label: $c-yellow-1
      color: "#f8f1df"
    - label: $c-grey-4
      color: "#d3d3d3"
    - label: $c-grey-3
      color: "#e9e9e9"
    - label: $c-grey-2
      color: "#f1f1f1"
    - label: $c-grey-1
      color: "#f8f8f8"
    - label: $c-white
      color: "#ffffff"