context:
    fileurl: https://sf.gov/sites/default/files/2018-07/Public%20Marriage%20License%20Application%20-%20MLPA.pdf
    field_file:
        isEmpty: false
        entity:
            label: Public marriage license application