title: "Content Head"
context:
  title: Get a San Francisco birth certificate
  description:  You can get a copy of a birth certificate for someone born in San Francisco after 1906. 
variants:
- name: default
  label: "No Image"
- name: With Image
  context:
    image: <img src="http://placeimg.com/300/300/nature" alt="Placeholder image" />