context:
    primary: |
      <li><a href="#">Primary Tab 1</a></li><li><a href="#">Primary Tab 2</a></li>
    secondary: |
      <li><a href="#">Secondary Tab 1</a></li><li><a href="#">Secondary Tab 2</a></li>