collated: true
default: dept
variants:
- name: With Related Department
  context:
    url: 
      url: "#"
    title: Get Affordable Housing
    body: Donec mollis hendrerit risus. Sed consequat, leo eget bibendum sodales, augue
      <a href="#">velit cursus</a> nunc, quis gravida magna.
    relatedDept: Related Dept
- name: No Related Department
  context:
    url: "#"
    title: Get Affordable Housing
    body: Donec mollis hendrerit risus. Sed consequat, leo eget bibendum sodales, augue
      <a href="#">velit cursus</a> nunc, quis gravida magna.
    