context:
    transaction_card: 
        title: Affordable Housing
        body: Donec mollis hendrerit risus. Sed consequat leo eget bibendum sodales augue velit cursus nunc quis gravida magna mi a libero. Donec id justo. Pellentesque posuere.
