context:
    url: https://sfbos.org/index.aspx?page=11322
    photo: "https://sf.gov/sites/default/files/2018-12/Screen%20Shot%202018-12-07%20at%206.40.45%20AM.png"
    first_name: "Malia"
    last_name: "Cohen"
    position_title: "Supervisor, President of the Board"
variants:
  - name: default
    label: Without subtitle
  - name: subtitle
    label: With subtitle
    context:
      position_subtitle: "District 10"
  - name: hero-default
    label: Hero without subtitle
    context:
      class: person-hero
  - name: hero-subtitle
    label: Hero with subtitle
    context:
      class: person-hero
      position_subtitle: "District 10"