title: Map
collated: true
context:
  width: 250
  height: 200
  langcode: en
  zoom: 16
  url_suffix: City%20Hall%2C%20Room%20168%20City%20Hall%2C%20Room%20168%20San%20Francisco%20CA
variants:
- name: default
  label: Default with address_text
  context:
    include_map: true
    map_type:
    address_text: 1231 Stevenson St
- name: static
  label: Static with link
  context:
    include_static_map: true
    include_link: true
    map_type:
    static_scale: 2
    static_map_type:
    apikey: AIzaSyAH-IyDGeuWBmZScFR3LmuQoU74K0GYHTI
    address_text: 
    link_text: Get directions