label: Checkboxes
context:
  # This set the data-id attribute, *not* the id attribute. It will also be
  # used as the input name(s) if no name (or per-option name) is provided.
  id: will_the_work_involve
  title: Will the work involve any of the following?
  # the array syntax should deserialize as an array of checked values
  name: 'work_involves[]'

  options:
  - title: Repairing or replacing the building's foundation
    value: foundation

  - title: Building a driveway or auto runway
    value: driveway

  - title: Using street space
    value: street-space

  - title: Changing the front facade
    value: facade

  - title: Repairing or changing the sidewalk above a basement
    value: sidewalk
