name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: npm ci
      # - run: npm test
      - run: gulp build

  publish:
    needs: build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12

      - name: publish setup
        run: |
          # this prevents `npm version` from committing to git
          npm config set git-tag-version false
          echo canary > DIST_TAG

      - name: tag latest
        if: github.ref == 'refs/heads/master'
        run: 'echo latest > DIST_TAG'

      - name: tag release candidate
        if: startsWith(github.ref, 'refs/heads/release-')
        run: |
          npm version "$(npx fx package.json .version)-rc.$(git rev-parse --short HEAD)"
          echo next > DIST_TAG

      - name: tag canary
        if: '!env.DIST_TAG'
        run: 'npm version "0.0.0-$(git rev-parse --short HEAD)"'

      - name: prepublish
        run: |
          echo "Publishing to dist-tag: '$(cat DIST_TAG)'..."
          npm run before-publish

      - name: publish
        run: 'npm publish --tag="$(cat DIST_TAG)" --dry-run'

      - name: postpublish
        run: npm run after-publish
