name: Publish to npm
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
      - run: gulp build

  publish:
    needs: build
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12

      - env:
          GIT_SHA: "$(git rev-parse --short HEAD)"
          GIT_BRANCH: "$(git symbolic-ref --short HEAD)"
          PACKAGE_VERSION: "$(npx fx package.json .version)"
          DIST_TAG: canary
        run:
          - echo "GIT_SHA: '$GIT_SHA'"
          - echo "GIT_BRANCH: '$GIT_BRANCH'"
          - echo "PACKAGE_VERSION: '$PACKAGE_VERSION'"
          - echo "DIST_TAG: '$DIST_TAG'"

      - name: tag latest
        if: env.GIT_BRANCH == 'master'
        env:
          DIST_TAG: latest

      - name: tag release candidate
        if: "startsWith(env.GIT_BRANCH, 'release-')"
        run: npm version "${PACKAGE_VERSION}-rc.${GIT_SHA}"
        env:
          DIST_TAG: rc

      - name: tag canary
        if: env.DIST_TAG == 'canary'
        run: npm version "0.0.0-${GIT_SHA}"

      - name: publish
        run: npm publish --tag="$DIST_TAG" --dry-run
