context:
  items:
    - title: "Featured item 1"
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum purus odio, ut dictum justo scelerisque ac. Quisque vitae nisl lectus. Morbi semper ante purus, eget porta magna eleifend at."
      url: "#item1"
    - title: "Featured item 2"
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum purus odio, ut dictum justo scelerisque ac."
      url: "#item2"
    - title: "Featured item 3"
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
      url: "#item3"
    - title: "Featured item 4"
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
      url: "#item4"
    - title: "Featured item 5"
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum purus odio, ut dictum justo scelerisque ac. Quisque vitae nisl lectus. Morbi semper ante purus, eget porta magna eleifend at."
      url: "#item5"
    - title: "Featured item 6"
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum purus odio, ut dictum justo scelerisque ac."
      url: "#item6"
    - title: "Featured item 7"
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum purus odio, ut dictum justo scelerisque ac. Quisque vitae nisl lectus."
      url: "#item7"
